### ISSUE TITLE
Broken for 6.4

### ISSUE THREAD

**Issue by rrbailey89** [akira0245/Kombatant#5]
This seems to be broken after the 6.4 patch. I suspect it has to do with changes to isDying.

**Comment by akira0245** [comment]
just pushed an update. please check if it is functioning properly🙂

**Comment by Dapvhir** [comment]
Woo you're alive! I can re-kill my fork XD thanks for updating!

**Comment by Dapvhir** [comment]
@akira0245 I can validate everything seems to be working, and thank you for updating yours so I didn't spend several hours figuring out putting the autotrade back in XD

StatusFlag changes were evil.
